name: 'Build backend'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Current directory
      run: ls

#    - name: Change directory
#      run: cd

    - name: Start docker compose
      run: docker-compose up