name: 'Autodeploy on main'

on:
  push:
    branches:
      - 'main'

jobs:
  sshconnect:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_GITHUB_ACTIONS }}
        known_hosts: ${{ secrets.SSH_SERVER_HOST }}

    - name: Check hosts
      run: cat ~/.ssh/known_hosts

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Check hosts
      run: cat ~/.ssh/known_hosts

    - name: Install RClone
      run: sudo apt install rclone -y

    - name: Version RClone
      run: rclone version

#    - name: Connect to server via SSH with Password
#      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }}
#    - name: Deploy with rsync
#      run: rsync -avz -e "ssh -p 22" hellofile.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }}:/home/ubuntu/dev/docker-app-backend/

    - name: Watch current directive
      run: ls

    - name: Go to current directive
      run: cd /home/dev/

#    - name: Create image and run docker container.
#      run: docker-compose up

#    - name: Check active containers status.
#      run: docker ps

#    - name: Check all containers status.
#      run: docker ps -a
