name: 'Autodeploy on main'

on:
  push:
    branches:    
      - 'main'

jobs:
  sshconnect:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_GITHUB_ACTIONS }}
        known_hosts: ${{ secrets.SSH_SERVER_HOST }} 

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz ./dist/ ubuntu@${{ secrets.SSH_SERVER_HOST }}:/home/ubuntu/dev/docker-app-backend/
  
    - name: Go to current directive
      run: cd /home/ubuntu/dev/

    - name: Create image and run docker container.
    run: docker-compose up

    - name: Check active containers status.
    run: docker ps

    - name: Check all containers status.
    run: docker ps -a 
