name: "Auto create Pull request to main"

on:
  push:
    branches:
      - 'staging'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: staging
          base: main
          delete-branch: false
          title: 'Merge: Staging to Main'
          body: |
            Merge report:
            - Updated with *today's* date
          labels: automated PR
          assignees: NolimitL
          reviewers: NolimitL
          team-reviewers: owners
          draft: false