name: "Auto create Pull request to main"

on:
  push:
    branches:
      - 'staging'

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          head: staging
          base: main
          title: "An automatically created PR!"